### ISSUE TITLE
Missing includeDeepSleep parameter

### ISSUE THREAD

**Issue by joevin-slq** [s1lviu/cordova-plugin-uptime#1]
Hello,

Visual Studio code shows me this error : 
![image](https://user-images.githubusercontent.com/14151398/39965984-33e026c2-56a4-11e8-96a0-8579e74dd874.png)

Because the index.d.ts file in node_modules/@ionic-native/uptime is missing the parameter :
```
import { IonicNativePlugin } from '@ionic-native/core';
/**
 * this.uptime.getUptime()
 *   .then(uptime => console.log(uptime))
 *   .catch(error => console.log(error));
 */
export declare class Uptime extends IonicNativePlugin {
    /**
     * This function return system uptime
     * @return {Promise<string>} Returns a promise that return the uptime in milliseconds
     */
    getUptime(): Promise<string>;
}
```

But this index.d.ts is generated by cordova so I think that in your last commit : https://github.com/s1lviu/cordova-plugin-uptime/commit/7e8b9a6185af52c0202c9a0c86cebd7153f94c5d

You missed to add the includeDeepSleep boolean parameter in the `www/Uptime.js` file.

**Comment by s1lviu** [comment]
Hi, @joedu12 
Yes, you are right. The code was written on my machine, but I forgot to push it. 
Can you check now?
Thanks!

**Comment by joevin-slq** [comment]
Hi, @s1lviu 
Yep, it seems to work with this package "@devrevolution/uptime": "^1.0.0" !
Thank you.
